meta:
    site_title: "千阳's blog"
    site_subtitle: "痛苦的日子才是最好的日子"
    site_language: "zh-cn"
    absolute_baseurl: http://qianyang.me
    domain: yanping.me
    author:
        full_name:Chen Yanping
        short_name&#58 ypchen
        name&#58 ypchen
        email&#58 chen@yanping.me

url: http://qianyang.me

#baseurl: /base

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: ypchenstory

      
css:
    - /css/screen.css


